# HW 5: Pandas Intro

#### Charlotte Strom
#### 9/15/26
#### GEOG 592

Using the cleaned CSV file from the previous homework, create a Jupyter Notebook that opens and explores the data using pandas.

Use the following methods:

df.head()

df.shape

df.columns

df.dtypes

df.info()

Also use a mask to create a dataframe with less rows.

In [24]:
import csv
# Read and inspect the raw dataset using csv.reader
file = "cleaned_Hospitals_NC.csv" # Specify the path to the CSV file

with open(file, "r", encoding="utf-8-sig") as file: # Open the CSV file in read mode with UTF-8 encoding
    reader = csv.reader(file) # This creates a CSV reader object to read the file
    rows = list(reader)

# Verify data structure by printing the first 10 rows
for row in rows[:10]: 
    print(row)

['X', 'Y', 'objectid', 'facility', 'licensee', 'expires', 'hgenlic', 'rehabhlic', 'psylic', 'salic', 'detoxlic', 'hoslic', 'rsrchlic', 'nfgenlic', 'othrhlic', 'alzlic', 'hivlic', 'tbilic', 'venlic', 'othnflic', 'rehabnlic', 'haalzlic', 'hahivlic', 'hagenlic', 'orheart_hl', 'orcsect_hl', 'orother_hl', 'oramsu_hl', 'orshare_hl', 'orendo_hl', 'altfacname', 'hltype', 'stype', 'fcounty', 'fcity', 'fstate', 'fzip', 'faddr1', 'fphone', 'licno']
['458186.754900001', '171439.614999998', '1', 'Carolinas HealthCare-Harrisburg', '', '', '7', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', 'Harrisburg Medical', 'ED', 'HL', 'Cabarrus', 'Harrisburg', 'NC', '28215', '9592 Rocky River Road', '904-403-9300', '']
['722755.4005', '63629.5810000002', '2', 'New Hanover Regional Medical Center-North', '', '', '10', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', 'NHRMC North', 'ED', 'HL', 'New Hanover', 'Wilmington', 'NC', '28111', '151 Scotts Hill Medical Dr', '910-662-9000', '']
['443409.280199997', '156439.008099999', '3', 'Carolinas HealthCare-SouthPark', '', '', '16', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', 'SouthPark', 'ED', 'HL', 'Mecklenburg', 'Charlotte', 'NC', '28211', '6965 Fairview Road', '704-631-1300', '']
['599693.785499997', '142181.160399999', '4', 'Cape Fear Valley-Hoke Hospital', 'Hoke Healthcare, LLC', '', '41', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', 'Hoke Hospital', 'ED', 'HL', 'Hoke', 'Raeford', 'NC', '28376', '210 Medical Pavilion Dr', '910-904-8000', 'H0288']
['564349.498499997', '256552.318999998', '5', 'Cone Health-Alamance Regional', 'Alamance Regional Medical Center, Inc.', '', '182', '0', '44', '12', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '2', '0', '3', '9', '4', 'Alamance Regional Medical Center', 'Hospital', 'HL', 'Alamance', 'Burlington', 'NC', '27216', '1240 Huffman Mill Rd', '(336)538-7450', 'H0272']
['294440.156099997', '179699.171500001', '6', 'UNC Health Care-Pardee', 'Henderson County Hospital Corporation', '', '193', '0', '21', '8', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', 'Margaret R Pardee Memorial Hospital', 'Hospital', 'HL', 'Henderson', 'Hendersonville', 'NC', '28791', '800 North Justice Street', '(828)696-1000', 'H0161']
['659037.044399999', '286502.8068', '7', 'Duke LifePoint-Maria Parham Medical Center', 'Maria Parham Medical Center, Inc.', '', '91', '11', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', 'Maria Parham Medical Center', 'Hospital', 'HL', 'Vance', 'Henderson', 'NC', '27536', '566 Ruin Creek Rd', '(252)436-1100', 'H0267']
['783740.802199997', '233516.217399999', '8', 'Martin General Hospital', 'Williamston Hospital Corporation', '', '49', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '2', '1', 'Martin General Hospital', 'Hospital', 'HL', 'Martin', 'Williamston', 'NC', '27892', '310 South McCaskey Rd', '(252)809-6179', 'H0078']
['492854.177000001', '259122.365499999', '9', 'Novant Health-Medical Park Hospital', 'Medical Park Hospital, Inc.', '', '22', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', 'Novant - Medical Park Hospital', 'S', 'HL', 'Forsyth', 'Winston Salem', 'NC', '27103', '1950 South Hawthorne Rd', '(336)718-0600', 'H0229']

In [25]:
import pandas as pd
filename = "cleaned_Hospitals_NC.csv" # Specify the path to the CSV file
df = pd.read_csv(filename) # Read the CSV file into a pandas DataFrame
type(df) # Check the type of the DataFrame

pandas.DataFrame

#### 1. Using df.head()

df.head() is a method, meaning that it performs an action using the object. In this case, the object has  bee set to be the DataFrame of cleaned_Hospitials_NC.csv 

df.head() displays the first 5 rows of the DataFrame

In [26]:
df.head()

,X,Y,objectid,facility,licensee,expires,hgenlic,rehabhlic,psylic,salic,...,altfacname,hltype,stype,fcounty,fcity,fstate,fzip,faddr1,fphone,licno
0,458186.7549,171439.6150,1,Carolinas HealthCare-Harrisburg,NaN,NaN,7,0,0,0,...,Harrisburg Medical,ED,HL,Cabarrus,Harrisburg,NC,28215,9592 Rocky River Road,904-403-9300,NaN
1,722755.4005,63629.5810,2,New Hanover Regional Medical Center-North,NaN,NaN,10,0,0,0,...,NHRMC North,ED,HL,New Hanover,Wilmington,NC,28111,151 Scotts Hill Medical Dr,910-662-9000,NaN
2,443409.2802,156439.0081,3,Carolinas HealthCare-SouthPark,NaN,NaN,16,0,0,0,...,SouthPark,ED,HL,Mecklenburg,Charlotte,NC,28211,6965 Fairview Road,704-631-1300,NaN
3,599693.7855,142181.1604,4,Cape Fear Valley-Hoke Hospital,"Hoke Healthcare, LLC",NaN,41,0,0,0,...,Hoke Hospital,ED,HL,Hoke,Raeford,NC,28376,210 Medical Pavilion Dr,910-904-8000,H0288
4,564349.4985,256552.3190,5,Cone Health-Alamance Regional,"Alamance Regional Medical Center, Inc.",NaN,182,0,44,12,...,Alamance Regional Medical Center,Hospital,HL,Alamance,Burlington,NC,27216,1240 Huffman Mill Rd,(336)538-7450,H0272

#### 2. df.shape

Shape is an attribute.

An attribute stores or reports information about the object.

The result has the form (rows, columns).

Also note that df.shape does NOT use ().

In [27]:
df.shape
# Returns the number of rows and columns in the DataFrame as a tuple (rows, columns)

(163, 40)

#### 3. df.columns

Returns the names of the columns in the DataFrame as a list. 

Note: it also returns the data type of the column names... which in this case, is str.

Once again, NO parethesis used

In [28]:
df.columns

Index(['X', 'Y', 'objectid', 'facility', 'licensee', 'expires', 'hgenlic',
       'rehabhlic', 'psylic', 'salic', 'detoxlic', 'hoslic', 'rsrchlic',
       'nfgenlic', 'othrhlic', 'alzlic', 'hivlic', 'tbilic', 'venlic',
       'othnflic', 'rehabnlic', 'haalzlic', 'hahivlic', 'hagenlic',
       'orheart_hl', 'orcsect_hl', 'orother_hl', 'oramsu_hl', 'orshare_hl',
       'orendo_hl', 'altfacname', 'hltype', 'stype', 'fcounty', 'fcity',
       'fstate', 'fzip', 'faddr1', 'fphone', 'licno'],
      dtype='str')

#### 4. df.dtypes

Returns the data type of each column in the DataFrame.

NO parentheses.

In [29]:
df.dtypes

X             float64
Y             float64
objectid        int64
facility          str
licensee          str
expires           str
hgenlic         int64
rehabhlic       int64
psylic          int64
salic           int64
detoxlic        int64
hoslic          int64
rsrchlic        int64
nfgenlic        int64
othrhlic        int64
alzlic          int64
hivlic          int64
tbilic          int64
venlic          int64
othnflic        int64
rehabnlic       int64
haalzlic        int64
hahivlic        int64
hagenlic        int64
orheart_hl      int64
orcsect_hl      int64
orother_hl      int64
oramsu_hl       int64
orshare_hl      int64
orendo_hl       int64
altfacname        str
hltype            str
stype             str
fcounty           str
fcity             str
fstate            str
fzip            int64
faddr1            str
fphone            str
licno             str
dtype: object

#### 5. df.info()

Provides a concise summary of the DataFrame.

Includes the number of non-null entries, data types of each column, and memory usage. 

Does use ().

In [30]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 163 entries, 0 to 162
Data columns (total 40 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   X           163 non-null    float64
 1   Y           163 non-null    float64
 2   objectid    163 non-null    int64
 3   facility    163 non-null    str
 4   licensee    136 non-null    str
 5   expires     3 non-null      str
 6   hgenlic     163 non-null    int64
 7   rehabhlic   163 non-null    int64
 8   psylic      163 non-null    int64
 9   salic       163 non-null    int64
 10  detoxlic    163 non-null    int64
 11  hoslic      163 non-null    int64
 12  rsrchlic    163 non-null    int64
 13  nfgenlic    163 non-null    int64
 14  othrhlic    163 non-null    int64
 15  alzlic      163 non-null    int64
 16  hivlic      163 non-null    int64
 17  tbilic      163 non-null    int64
 18  venlic      163 non-null    int64
 19  othnflic    163 non-null    int64
 20  rehabnlic   163 non-null    int64
 21  haalzlic    163 non-null    int64
 22  hahivlic    163 non-null    int64
 23  hagenlic    163 non-null    int64
 24  orheart_hl  163 non-null    int64
 25  orcsect_hl  163 non-null    int64
 26  orother_hl  163 non-null    int64
 27  oramsu_hl   163 non-null    int64
 28  orshare_hl  163 non-null    int64
 29  orendo_hl   163 non-null    int64
 30  altfacname  150 non-null    str
 31  hltype      163 non-null    str
 32  stype       163 non-null    str
 33  fcounty     163 non-null    str
 34  fcity       163 non-null    str
 35  fstate      163 non-null    str
 36  fzip        163 non-null    int64
 37  faddr1      163 non-null    str
 38  fphone      163 non-null    str
 39  licno       136 non-null    str
dtypes: float64(2), int64(26), str(12)
memory usage: 51.1 KB

#### 6. Use a mask to create a dataframe with less rows

Creating a mask to return only emergency rooms.

In [31]:
Emergency_Rooms_NC = df["hltype"] == "ER"
Emergency_Rooms_NC

0      False
1      False
2      False
3      False
4      False
       ...
158    False
159    False
160    False
161    False
162    False
Name: hltype, Length: 163, dtype: bool

Mask all the rows of hospitals that are in Raleigh.

In [32]:
mask = df["fcity"].str.startswith("Raleigh", na=False)
df2 = df[mask]
df2

,X,Y,objectid,facility,licensee,expires,hgenlic,rehabhlic,psylic,salic,...,altfacname,hltype,stype,fcounty,fcity,fstate,fzip,faddr1,fphone,licno
62,644076.1787,230618.7748,63,Duke Raleigh Hospital,"Duke University Health System, Inc.",NaN,186,0,0,0,...,Duke Raleigh Hospital,Hospital,HL,Wake,Raleigh,NC,27611,3400 Wake Forest Rd,(919)954-3000,H0238
93,636423.7128,229391.0873,94,UNC Health Care-Rex Healthcare,"Rex Hospital, Inc.",NaN,388,0,0,0,...,Rex Healthcare,Hospital,HL,Wake,Raleigh,NC,27607,4420 Lake Boone Trail,(919)784-3100,H0065
113,646840.8762,225821.0245,114,WakeMed,WakeMed,NaN,628,0,0,0,...,WakeMed,Hospital,HL,Wake,Raleigh,NC,27620,3000 New Bern Ave,(919)350-8000,H0199
121,645763.7579,239619.9485,122,WakeMed North Family Health & Women's Hospital,NaN,12:00:00 AM,61,0,0,0,...,WakeMed North Healthplex,Hospital,HL,Wake,Raleigh,NC,27614,10000 Falls of Neuse Road,919-350-8000,NaN
139,628975.0713,240603.3754,140,WakeMed Brier Creek Healthplex,NaN,NaN,12,0,0,0,...,WakeMed Brier Creek Healthplex,ED,HL,Wake,Raleigh,NC,27617,8001 T.W. Alexander Drive,919-350-8000,NaN
152,647011.0428,225437.4678,153,"Holly Hill Hospital, L.L.C.","Holly Hill Hospital, LLC",NaN,0,0,205,0,...,NaN,Psych,MHH,Wake,Raleigh,NC,27610,3019 Falstaff Rd,(919)250-7000,MHH0113